### PR TITLE
Add find-alternative script

### PR DESCRIPTION
**Pull request by j3k0**
See #26

### CODE REVIEW

**Comment by j3k0** [comment]
See #26

**Comment by j3k0** [comment]
I should have mentioned, this has to run on a server/computer with no direct access to the database. Just to the public API endpoint `<BASE_URL>/users/alias/tag/:tag`

**Comment by elmigranto** [comment]
> I should have mentioned, this has to run on a server/computer with no direct access to the database. Just to the public API endpoint `<BASE_URL>/users/alias/tag/:tag`

Okay. Added bool flag to do that (`true` by default), [everything pulled from env](https://github.com/j3k0/ganomede-directory/blob/master/lib/client.js#L29), though you'll have to specify `API_SECRET=anything` so `require('./config')` works; it doesn't actually used, so you can put anythgin there.

**Comment by elmigranto** [comment]
Tried running it against https://prod.xxx.xxx, but that seems down.

**Pull request merged**
