### PR TITLE
User creation response includes aliases

### PR DESCRIPTION
**Pull request by elmigranto**
Looks like events emitted from users always include full user profile. But calls to directory endpoints (creating or editing user) don't reply with full profile. So we'll need to fetch profiles every time.

I was thinking we add that to some endpoints. Creation seems easy, but I guess we'll have to query profile anyways, to keep things consistend (i.e. it does not make much sense to include that in login request).

What do you think?

### CODE REVIEW

**Comment by j3k0** [comment]
Let's just emit events containing info known to the server. The worker can fetch the missing pieces if he needs them

**Comment by elmigranto** [comment]
What seems to be always known is `userId`, so `{data: {userId}}` then?

Also, do we emit only from `directory-client`'s `#addAccount`, `#editAccount`, `#authenticate()`. Looks like a correct place to me…

**Comment by j3k0** [comment]
Let's include aliases when they are know: `{data: {id, {aliases}}`, this prevents worker to have to fetch information when they're already known. For instance, mailchimp worker will only be interested in user's email. Emails will only change from places where email is known, so can be included in the event.

**Comment by j3k0** [comment]
As per making the change in `directory-client`. I'd rather have a higher level module take care of that. Maybe a final middleware added to users-api requests.

Why? Because maybe we'll also want to integrate informations that are not stored in directory, but as metadata (like the user's country, language, birthday, etc.)

**Comment by elmigranto** [comment]
Yeah, I don't think including profile on changes is a good idea, thought initially it would only be required for user creation, but that's not the case and changing other endpoints doesn't sound good to me either.

**Pull request closed without merging**
