### PR TITLE
feature/remove-todos

### PR DESCRIPTION
**Pull request by elmigranto**
#12

### CODE REVIEW

**Comment by elmigranto** [comment]
I fixed all the stuff that was bugged or incomplete. I commented on some things that are okay to leave as is for now. And I didn't touch anything under `./tests/` (it either calls for quite a refactor or automating db inits/drops which I don't think too useful).

Though I would like you to look at:

  - [`errors.js`](https://github.com/j3k0/ganomede-directory/blob/fd5d984248cc7a134f8b6a0dcfc7f3370c204def/src/errors.js) to get your general opinion about what's going with error handling. When we have something good, let's pull it to `boilerplate` and maybe back port to other services next time we work on them;
  - [`ActionsExecutor#runChecks()` method](https://github.com/j3k0/ganomede-directory/blob/fd5d984248cc7a134f8b6a0dcfc7f3370c204def/src/ActionsExecutor.js#L26) — let's say we create a user with id `elmigranto` and email `elmigranto@example.com`. But those are already in database, and some time we might return "ID already taken" and sometime "Email already taken". If that's a problem, let's fix it:
    - we can either run checks in series (easier);
    - or we run all of them and return mulitple errors.
  - [this](https://github.com/j3k0/ganomede-directory/blob/fd5d984248cc7a134f8b6a0dcfc7f3370c204def/src/users/Profile.js#L3) and things under `./tests/` (refactor actions so we can test them more meaningfuly and automate db creation) should be fine to leave for now.

Let me know if we want to change anyting from the list above.

<hr/>

Overall, this is safe to merge and stuff will run correctly/safely.

**Comment by j3k0** [comment]
> errors.js

It good. However I'd not make all use-case specific errors part of the same module. Also maybe rename `BaseError` into `GanomedeError`?

(UserAlreadyExistsError, AliasAlreadyExistsError, UserNotFoundError, InvalidAuthTokenError, InvalidCredentialsError, RequestValidationError)

In term of what could be improved, I'd say being able to add some raw data to the error could be useful sometimes. An example: `AliasAlreadyExistsError` could benefit form having a field like `"aliasType": "email"`, so we can know programmatically which field is causing problem... But it seems like restify RestError doesn't allow it, so let's forget that...

**Comment by j3k0** [comment]
> ActionsExecutor#runChecks()

Ok, it's minor. I think we can consider that it doesn't matter.

**Comment by j3k0** [comment]
> Profile.js

We're not gonna have hundreds of aliases (or just very rarely -- some "dumb" user that changes its username twice a day... why not..). No need to optimize something that will probably never noticeably affect performances.

**Comment by elmigranto** [comment]
About errors. Sure, we should pull all the service-specific stuff. For more info on error, see, for example, [`AliasAlreadyExistsError`](https://github.com/j3k0/ganomede-directory/blob/fd5d984248cc7a134f8b6a0dcfc7f3370c204def/src/errors.js#L80) you mentioned, it has all that, just redefine `constructor` and attach w/ever.

**Comment by j3k0** [comment]
About errors, when I said:

> [add custom data...] so we can know programmatically which field is causing problem

I meant on the client. Are custom data attached to the error objects sent in the reply?

**Comment by elmigranto** [comment]
[No](https://github.com/j3k0/ganomede-directory/blob/fd5d984248cc7a134f8b6a0dcfc7f3370c204def/src/errors.js#L130). It's just `statusCode` (`error.statusCode`), `restCode` (`error.name` which is usually `error.consturctor.name`) and `message` (`error.message`). I see what you mean and I'll add some way to enhance JSON response in boilerplate.

**Comment by j3k0** [comment]
That's what I thought. Again, if restify.RestError doesn't not support additional field, then we can forget about that for now, it's nothing major nor urgent.

**Pull request merged**
